### PR TITLE
WIP: Add json methods to library

### PR DESCRIPTION
**Pull request by Apollon77**
Hi,

I currently adapt a nodejs native module to introduct libmbus into nodejs and therefor I base on the great work of https://github.com/samkrew/libmbus .
I can not reach samkrew and also he did not updated the underlaying libmbus repo sometime, but verified his work after re-applying his changes on the current state of the libmbus github repo.

So I would like to bring in this pull request to add json output methods into the library. 

If I should change anything please tell me what and I will be happy to do so.

Greetings,

Ingo

### CODE REVIEW

**Comment by Apollon77** [comment]
I added one commit to correctly return ISO conform timestamps with "Z" at the end

**Comment by lategoodbye** [comment]
Hi Ingo,
sorry for my late reply and thank for you contribution.
I see two reason why i can't merge this request. First reason is that the change only apply to the old API mbus-protocol.c and not mbus-protocol-aux.c. Second reason is that i don't want to add any additional output formats which we need to maintain.
How about converting libmbus XML output to JSON (xlst)?

Nevertheless the commit 29a9e5a looks great, please make a separate pull request i will merge it ASAP. It would be nice to have the timestamps in mbus-protocol-aux.c in the same format, too.

Stefan

**Comment by Apollon77** [comment]
Hi Stefan,

"old API"? What's the new?
The reason would mainly be performance, but I understand you.

Timestamps: Will see what I can do.

**Comment by lategoodbye** [comment]
I'm fine with the timestamp changes and there is no problem with the whitespace fixes.

**Comment by Apollon77** [comment]
So build/configure stuff should be removed?!

**Comment by lategoodbye** [comment]
Yes, these are unrelated and even without a helpful commit message.

**Comment by Apollon77** [comment]
The build and configure changes came from https://github.com/samkrew/libmbus/commit/b1ad2f6100114c0cbbee88763be25073560109c7 ... I try to revert then and see if ci still builds. 

BTW: could you also please have a look at #133?! ;-)

**Comment by Apollon77** [comment]
Ok, after reverting changes to configure/build the compile using gcc on macOS failed: https://travis-ci.org/Apollon77/libmbus/jobs/352707224

After adding back one "autoreconf" in build.sh it works again ... so for macos this change seems to be needed.
https://travis-ci.org/Apollon77/libmbus/jobs/352709971

With this reasone is this change acceptable?!

**Comment by lategoodbye** [comment]
As i said before without a self-explaining commit message i cannot accept such changes. I confess some of my old commit aren't always better, but in case of a regression reverting is much easier to follow.

**Comment by lategoodbye** [comment]
Should i make a suggestion for the commit message?

**Comment by Apollon77** [comment]
No, everything good. Had no time to follow up this week. And (because bound a bit somehow) a firt feedback to #133 would be also helpful that I know how to proceed.
Reason is that the PR from #133 is based on #132 in my fork, so when doing the needed reset and re-commits for #132 I also need to rebase 133 and such ...

**Comment by lategoodbye** [comment]
That's bad. Your pull requests must be independent. As i said before please make a fresh, separate pull request for the fixes (with proper commit messages and without reverts).

**Comment by Apollon77** [comment]
I know ... I will fix that soon

**Comment by lategoodbye** [comment]
What's the state of the timestamp changes?

**Comment by Apollon77** [comment]
As soon as the nodejs module now ist stable I will start reset my fork to your codebase and clean up anything and then send you clean PRs for several things ... And after this I will re-do the windows branch ... give me some days :-) I need to get a clean base for this first

**Comment by Apollon77** [comment]
I still try to reproduce the macos build problem. Currently it works also without the one "autoreconfigure" line, but I also had issues in some build tries ... I do not understand it. As soon as I can reproduce it I will open a new issue/pr

**Pull request closed without merging**
