### PR TITLE
Update libmbus

### PR DESCRIPTION
**Pull request by arska**
Please merge @lategoodbye s excellent work back into the main repository

### CODE REVIEW

**Comment by lategoodbye** [comment]
@arska 

Unfortunately it's not so easy. There has been a discussion about some commits (changes in serial handling) and Robert had some concerns about that. I want to respect that.

Another problem is that i don't have a real test environment anymore.

Here is my suggestion:
Could you please write down the hashes of important changes from my repository here and i will create a clean pull request and merge it.

**Comment by arska** [comment]
I think it is a pity to split the (little) attention this project receives into different repositories. When I have a problem with a new device (about once a year) it is painful to merge and the time used for that is gone for improvements, new test cases, etc :(

From looking at #67 I don't see any massive conflicts of opinions, to resolve that I propose to leave the default as-is and add an user configurable option (e.g. command line flag) to "use alternative serial port configuration" for platforms where that is helpful.

@lategoodbye (and @rscada as well of course) I can give you access to my personal testbed (raspi, usb/serial, 4 m-bus slaves) and I have access to ~10 installations, please send me a ssh public key via email.

Best regards,
Aarno

**Comment by rscada** [comment]
Please go ahead and sync up this repo with the latest from @lategoodbye 

Unfortunately I don't have time to work on this project anymore (not even working in this industry any more). I think @lategoodbye has done a lot of great work and I think too it would be a pity if there is a split between the repos, as that only creates a confusing situation for existing and future users that might want to pick up this project for further development.

I think the best way forward would be to sync this repo with @lategoodbye latest repo, even if it cannot be fully tested (maybe @arska can help with that?)

**Comment by lategoodbye** [comment]
@arska I hope it's okay for you if i create a clean pull request to merge my change into this repository. I can't merge this pull request because a lot of commits contains more changes than expected from the log. Also the author of a commit should be kept.

The reason of forking is to play with new feature. Forking is not the problem, it is the missing clean pull request to merge the results back.

**Comment by arska** [comment]
@lategoodbye absolutely. I'll open a new pull request with my two commits. Do you have time to work on this today ?

I agree on the missing clean pull request, although it might motivate contributions if the project doesn't look abandoned :)

Cheers,
Aarno

**Pull request closed without merging**
