### PR TITLE
Improve test cases

### PR DESCRIPTION
**Pull request by arska**

### CODE REVIEW

**Comment by arska** [comment]
working on this, can you merge your commits, preferably including XML ?

https://github.com/lategoodbye/libmbus/commit/e33808ac8fe616625d17b603d9c09c91a52f5e4a
https://github.com/lategoodbye/libmbus/commit/948f384de2114c3e1c41df4a482d02cb1e94a0a1

**Comment by arska** [comment]
comment fixed

**Comment by lategoodbye** [comment]
Sorry for merging my pull request first.

Could you please fix that?

Btw it would be nice if you add the new product strings for the new test cases.

**Comment by arska** [comment]
@lategoodbye resolved merge conflict, will add product strings in separate PR, please merge

**Pull request merged**
